# Generated by Django 2.1 on 2019-05-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='ag',
            new_name='age',
        ),
    ]
