# Generated by Django 2.1 on 2019-05-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='datae',
            new_name='date',
        ),
    ]
